== Converting Asciidoc Files to Neo4j Browser Guides

This program uses AsciiDoctor ERB templates to generate an outline HTML and a slide for each level two header.

=== Create HTML

The following command will convert the AsciiDoc files in _guide/docs_ to HTML:

 $ ./gradlew convert

The HTML files are available in the _build/browser-guide_ directory at the root of this repository.

=== Start Local Server

In a new terminal, run the following command to start a local HTTP server:

[source,console]
----
$ ./gradlew httpServer
----

=== View in Neo4j Browser

To view this guide in the Neo4j Browser, type the following command in the action bar:

----
:play http://localhost:35729/browser-guide/index.html
----

[TIP]
====
You can use the `--continuous` flag to automatically convert the AsciiDoc files to HTML when the content is updated:

[source,console]
----
$ ./gradlew convert --continuous
----
====

You can find more details on how to create guides and their format at https://neo4j.com/developer/guide-create-neo4j-browser-guide/
